# Generated by Django 4.1.7 on 2024-05-05 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="addresscontact",
            table="addresscontact",
        ),
        migrations.AlterModelTable(
            name="entityaddress",
            table="entityaddress",
        ),
    ]
